const data = {
  products: [
    {
      _id: "1",
      name: "pretty women",
      category: "women",
      image: "p1.jpg",
      price: 120,
      brand: "Pretty",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Women Style",
    },
    {
      _id: "2",
      name: "pull women",
      category: "women",
      image: "p2.jpg",
      price: 120,
      brand: "Pull",
      rating: 4,
      numReviews: 20,
      description: "High Quality Women Style",
    },
    {
      _id: "3",
      name: "mega women",
      category: "women",
      image: "p3.jpg",
      price: 130,
      brand: "Awsome",
      rating: 3.5,
      numReviews: 30,
      description: "High Quality Women Style",
    },
    {
      _id: "4",
      name: "super women",
      category: "women",
      image: "p4.jpg",
      price: 140,
      brand: "Gorgeous",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Women Style",
    },
    {
      _id: "5",
      name: "lovely women",
      category: "women",
      image: "p5.jpg",
      price: 100,
      brand: "flop",
      rating: 2.5,
      numReviews: 16,
      description: "High Quality Women Style",
    },
  ],
};
export default data;
